(()=>{
 'use strict';const $=id=>document.getElementById(id),pairs={'client-from':['의뢰자','출발지'],'client-to':['의뢰자','도착지'],'from-to':['출발지','도착지']};let rules=[],client=null,locked=false;
 const endpoint=(address,detail)=>String(address||'').trim().replace(/\s+/g,'').toLowerCase()+'|'+String(detail||'').trim().replace(/\s+/g,'').toLowerCase();
 function match(){if(!window.TH_PORTAL?.profile||!$('order'))return null;const f=$('order').elements;const a=endpoint(f.from.value,f.fromDetail.value),b=endpoint(f.to.value,f.toDetail.value);return rules.find(r=>r.endpoint_a===[a,b].sort()[0]&&r.endpoint_b===[a,b].sort()[1])||null;}
 const label=p=>p?.method==='split'?pairs[p.pair][0]+' '+p.ratio+'% / '+pairs[p.pair][1]+' '+(100-p.ratio)+'%':p?.method||'주문마다 선택';
 async function load(id){rules=[];client=id;if(id)rules=await window.TH_API.rpc('th6_contract_list',{p_client:id});sync();}
 function sync(){if(!$('order'))return;const rule=match(),p=rule?.payment,shouldLock=Boolean(p?.method);if(locked&&!shouldLock){for(const id of ['paymentMethod','splitPayment','splitPair','splitRatio'])if($(id))$(id).disabled=false;}locked=shouldLock;
  if(shouldLock){$('paymentMethod').value=p.method==='split'?'신용':p.method;$('splitPayment').checked=p.method==='split';if(p.method==='split'){$('splitPair').value=p.pair;$('splitRatio').value=String(p.ratio);}for(const id of ['paymentMethod','splitPayment','splitPair','splitRatio'])$(id).disabled=true;}
  if(shouldLock){$('splitFields').hidden=p.method!=='split';const names=pairs[p.pair]||pairs['from-to'];$('splitHint').textContent=names[0]+' '+p.ratio+'% / '+names[1]+' '+(100-p.ratio)+'%';for(const opt of $('splitRatio').options){const n=Number(opt.value);opt.textContent=names[0]+' '+n+'% / '+names[1]+' '+(100-n)+'%';}}
  const note=$('contractNote');if(note){note.hidden=!rule;const stops=window.TH_ORDER?.routeLocations().length>2;note.textContent=rule?'약정 편도요금 '+rule.fare.toLocaleString('ko-KR')+'원'+(shouldLock?' · '+label(p)+' 고정':'')+(stops?' · 경유지 포함: 담당 영업자 확인 후 최종 요금 확정':''):'';}
 }
 function splitLabels(){return pairs[$('splitPair')?.value]||pairs['from-to'];}
 function data(){const r=match();return r?{id:r.id,fare:r.fare,payment:r.payment}:null;}
 function decorate(r,ui){const {card,extra,adjustment,enabled,fields,price,reason,consent}=ui;const stops=Math.max(0,(r.payload?.locations?.length||0)-2);let local=null,manual=null;
  if(stops){const panel=document.createElement('div');panel.className='contract-warning';panel.innerHTML='<strong>경유지 포함 · 운행요금 확정 필요</strong>';local=document.createElement('input');local.type='checkbox';const line=document.createElement('label');line.className='inline';line.append(local,document.createTextNode('관내 경유 · 1곳당 7,000원 추가'));panel.append(line);manual=document.createElement('input');manual.type='checkbox';const check=document.createElement('label');check.className='inline';check.append(manual,document.createTextNode('경유 경로와 최종 요금을 확인했습니다.'));panel.append(check);card.insertBefore(panel,adjustment);enabled.checked=true;enabled.disabled=true;enabled.closest("label").hidden=true;fields.hidden=fields.disabled=false;price.value='';const original=r.payload?.quote?.total;
   local.onchange=()=>{price.value=local.checked&&Number.isFinite(original)?original:'';price.readOnly=local.checked;manual.checked=false;consent.checked=false;if(local.checked&&!Number.isFinite(original))window.alert('거리·추가요금이 확인되지 않았습니다. 최종 요금을 직접 입력해 주세요.');};
  }
  let save=null,savePrice=null,fixed=null,method=null,pair=null,ratio=null;
  if(r.client_id&&!stops&&r.payload?.service==='일반 배송'){
   const details=document.createElement('details');details.className='contract-settings';const summary=document.createElement('summary');summary.textContent='이 구간 요금 · 결제 저장';details.append(summary);save=document.createElement('input');save.type='checkbox';const saveLabel=document.createElement('label');saveLabel.className='inline';saveLabel.append(save,document.createTextNode('다음 직행 주문부터 이 구간 요금 저장'));details.append(saveLabel);
   savePrice=document.createElement('input');savePrice.type='number';savePrice.min=1000;savePrice.max=2000000;savePrice.step=1000;const priceLabel=document.createElement('label');priceLabel.textContent='저장할 편도 약정요금 (추가금 제외)';priceLabel.append(savePrice);details.append(priceLabel);
   const rows=r.payload?.quote?.rows||[];const base=rows[0]?.amount;const extraAmount=rows.slice(1).some(x=>Number(x.amount)>0);if(!extraAmount)savePrice.value=price.value||base||'';price.addEventListener('input',()=>{if(!extraAmount)savePrice.value=price.value;});
   fixed=document.createElement('input');fixed.type='checkbox';const fixedLabel=document.createElement('label');fixedLabel.className='inline';fixedLabel.append(fixed,document.createTextNode('결제 방법 · 분담 비율도 고정'));details.append(fixedLabel);
   const select=(label,choices)=>{const el=document.createElement('select');el.setAttribute('aria-label',label);for(const [value,name] of choices){const o=document.createElement('option');o.value=value;o.textContent=name;el.append(o);}const l=document.createElement('label');l.textContent=label;l.append(el);details.append(l);return el;};
   method=select('결제 방법',[['신용','신용 · 의뢰자 결제'],['선불','선불 · 출발지 결제'],['착불','착불 · 도착지 결제'],['split','요금 나눠내기']]);pair=select('분담 방식',Object.entries(pairs).map(([k,v])=>[k,v.join(' ↔ ')]));ratio=select('분담 비율',Array.from({length:9},(_,i)=>[String((i+1)*10),String((i+1)*10)+'% / '+String(90-i*10)+'%']));ratio.value='50';const update=()=>{pair.parentElement.hidden=ratio.parentElement.hidden=method.value!=='split';};method.onchange=update;update();
   const hint=document.createElement('p');hint.className='portal-note';hint.textContent='같은'+' 의뢰자의 양방향 직행 구간에만 저장됩니다. 야간·급송·왕복 등 추가금은 별도로 계산합니다.';details.append(hint);card.append(details);
  }
  return {args(){if(stops&&(!manual.checked||!price.value||!consent.checked))throw Error('경유지 최종 요금과 고객 확인을 완료해 주세요.');if(local?.checked&&!Number.isFinite(r.payload?.quote?.total))throw Error('최종 운행요금을 직접 입력해 주세요.');if(save?.checked&&(!savePrice.reportValidity()||Number(savePrice.value)<1000))throw Error('저장할 편도 약정요금을 입력해 주세요.');return {p_save_fare:save?.checked?Number(savePrice.value):null,p_payment:save?.checked&&fixed.checked?{method:method.value,...(method.value==='split'?{pair:pair.value,ratio:Number(ratio.value)}:{})}:null,p_stop_mode:stops?(local.checked?'local':'manual'):null};}};
 }
 async function clientRules(id,root){root.replaceChildren();if(!id)return;const list=await window.TH_API.rpc('th6_contract_list',{p_client:id});for(const r of list){const row=document.createElement('div');row.className='contract-rule';const text=document.createElement('p');text.textContent=r.label_a+' ↔ '+r.label_b+' · '+r.fare.toLocaleString('ko-KR')+'원 · '+label(r.payment);const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent='저장 해제';b.onclick=async()=>{b.disabled=true;try{await window.TH_API.rpc('th6_contract_disable',{p_id:r.id});await clientRules(id,root);}catch(e){window.alert(e.message);b.disabled=false;}};row.append(text,b);root.append(row);}if(!list.length)root.textContent='저장된 구간 요금이 없습니다. 주문 승인 시 저장할 수 있습니다.';}
 window.TH_CONTRACT={load,match,data,sync,label,splitLabels,decorate,clientRules};
 if($('order')){$('order').addEventListener('change',()=>{sync();queueMicrotask(sync);});$('order').addEventListener('input',sync);}
})();
